gsutil -m cp \
  "gs://wcdi_production/heat_module/CMIP5_maxwetbulb_days_ge26.nc" \
  "gs://wcdi_production/heat_module/CMIP5_maxwetbulb_days_ge28.nc" \
  "gs://wcdi_production/heat_module/CMIP5_maxwetbulb_days_ge30.nc" \
  "gs://wcdi_production/heat_module/CMIP5_maxwetbulb_days_ge32.nc" \
  "gs://wcdi_production/heat_module/CMIP5_maxwetbulb_days_gehist_meantemp_max10.nc" \
  "gs://wcdi_production/heat_module/CMIP5_maxwetbulb_meantemp_max10.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tas_human_niche.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tas_mean.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_days_ge15.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_days_ge32.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_days_ge35.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_days_ge38.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_days_gehist_meantemp_max10.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_days_le0.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_mean.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmax_meantemp_max10.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmin_days_ge20.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmin_days_ge25.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmin_days_le0.nc" \
  "gs://wcdi_production/heat_module/CMIP5_tasmin_mean.nc" \
  "gs://wcdi_production/heat_module/globalREMO_maxwetbulb_days_ge26.nc" \
  "gs://wcdi_production/heat_module/globalREMO_maxwetbulb_days_ge28.nc" \
  "gs://wcdi_production/heat_module/globalREMO_maxwetbulb_days_ge30.nc" \
  "gs://wcdi_production/heat_module/globalREMO_maxwetbulb_days_ge32.nc" \
  "gs://wcdi_production/heat_module/globalREMO_maxwetbulb_days_gehist_meantemp_max10.nc" \
  "gs://wcdi_production/heat_module/globalREMO_maxwetbulb_meantemp_max10.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tas_mean.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmax_days_ge32.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmax_days_ge35.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmax_days_ge38.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmax_days_le0.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmax_mean.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmin_days_ge20.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmin_days_ge25.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmin_days_le0.nc" \
  "gs://wcdi_production/heat_module/globalREMO_tasmin_mean.nc" \
  data/. ;
